### PR TITLE
Persist login state after refresh

### PR DESCRIPTION
**Pull request by devotis**
After login also redirect back to state that was requested before
login. This helps in case of bookmarking url’s of states behind login

connect to #16

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by richardpringle** [comment]
ok to test

**Comment by crandmck** [comment]
@superkhau @devotis Does this require a doc update to https://docs.strongloop.com/display/LB/Getting+started+part+II or anywhere else ?

**Comment by superkhau** [comment]
@crandmck Not really, but you can mention it. Basically the user stays logged in even if the page is refreshed (which isn't happening now).

**Comment by devotis** [comment]
If there's anything more I can do for this PR, let me know.

**Comment by crandmck** [comment]
OK, so https://docs.strongloop.com/display/LB/Create+AngularJS+client includes some of the source code, so I'll update it once this is merged.

**Comment by superkhau** [comment]
@devotis Can you rebase? Let's land this.

**Comment by devotis** [comment]
@superkhau My branch is not behind of strongloop/master. No need to do a rebase.

**Comment by superkhau** [comment]
test please

**Comment by superkhau** [comment]
@slnode test please

**Comment by superkhau** [comment]
@devotis You're right, I'll try to rerun the tests again.

**Comment by superkhau** [comment]
Closed in favour of #27. @devotis I helped you rebase to get this landed quicker. Thanks for the contribution! :+1:

**Comment by superkhau** [comment]
Thanks for the contribution! ;)

**Pull request closed without merging**
